server:
  port: 8081

spring:
  application:
    name: ${APP_NAME}

  cloud:
    config:
      server:
        git:
          uri: ${GIT_URL}

  boot:
    admin:
      client:
        url: http://localhost:8080
        username: admin
        password: admin
        instance:
          service-url: http://localhost:8081

  management:
    endpoints:
      web:
        exposure:
          include: "*"